name: diseases
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  avatar_glow: ^2.0.2
  speech_to_text: ^6.3.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  fluro: ^2.0.5
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.4
  tflite_flutter: ^0.10.3
flutter_native_splash:
  android: true
  ios: true
  image: assets/images/first_logo.png
  color: "42a5f5"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/model.tflite

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
